### ISSUE TITLE
Symfony 6.1 Support

### ISSUE THREAD

**Issue by mehmetsen80** [kreait/firebase-bundle#42]
### Describe the feature you would like to see

I see you don't support Symfony 6.1 version.  I get this when I run   

`composer require kreait/firebase-bundle`

```
 Problem 1
    - google/cloud-core[v1.42.0, ..., v1.42.2] require guzzlehttp/psr7 ^1.2 -> found guzzlehttp/psr7[1.2.0, ..., 1.9.0] but the package is fixed to 2.4.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - google/cloud-core[v1.43.0, ..., v1.47.2] require monolog/monolog ^1.1|^2.0 -> found monolog/monolog[1.1.0, ..., 1.27.1, 2.0.0, ..., 2.8.0] but the package is fixed to 3.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - kreait/firebase-bundle 4.1.0 requires kreait/firebase-php ^6.0 -> satisfiable by kreait/firebase-php[6.0.0, ..., 6.9.1].
    - kreait/firebase-php[6.3.0, ..., 6.9.1] require google/cloud-core ^1.44.2 -> satisfiable by google/cloud-core[v1.44.2, ..., v1.47.2].
    - kreait/firebase-php[6.0.0, ..., 6.2.0] require google/cloud-core ^1.42.2 -> satisfiable by google/cloud-core[v1.42.2, ..., v1.47.2].
    - Root composer.json requires kreait/firebase-bundle ^4.1 -> satisfiable by kreait/firebase-bundle[4.1.0].

```

**Comment by jeromegamez** [comment]
The bundle explicitly support Symfony 6.x (you can check in its `composer.json`).

The snippet you posted is quite specific on the issue though 😅: `google/cloud-core` requires `psr/log ^1.0|^2.0` but it is fixed to `3.2` in your project's `composer.json`.

Luckily I know why this happens (otherwise your minimal bug description wouldn't have helped me reproduce the issue).

The latest Monolog version requires at least `psr/log` 3.0, the Google Cloud library supports only versions 1 and 2.

https://github.com/googleapis/google-cloud-php/pull/5334 aims add adding support for `psr/log` 3.x, but that's outside of the scope of the bundle or the underlying SDK.
